---
- name: create VG
  lvg:
    vg: "{{ tsuruController_nameVG }}"
    pvs: "{{ tsuruController_device }}"
    state: present

- name: create LVs for all APIs
  lvol:
    vg: "{{ tsuruController_nameVG }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
  with_items:
    - name: nosql
      size: "{{ tsuruController_sizeNoSQL }}"
    - name: inmem
      size: "{{ tsuruController_sizeInMem }}"
  failed_when: false #WORKAROUND FOR BUG https://github.com/ansible/ansible-modules-extras/issues/428

- name: create filesystems for all APIs
  filesystem:
    fstype: "{{ tsuru_fstype }}"
    dev: "/dev/{{ tsuruController_nameVG }}/{{ item }}"
    resizefs: false
  with_items:
    - nosql
    - inmem

- name: mount filesystems for all APIs
  mount:
    name: "{{ item.name }}"
    src: "/dev/{{ tsuruController_nameVG }}/{{ item.src }}"
    fstype: "{{ tsuru_fstype }}"
    state: present
  with_items:
    - name: "/var/lib/mongo"
      src: "nosql"
    - name: "/var/lib/redis"
      src: "inmem"

- block:
    - name: create prometheus LV for metrics master
      lvol:
        vg: "{{ tsuruController_nameVG }}"
        lv: "metrics"
        size: "{{ tsuruController_sizeMetrics }}"

    - name: create prometheus filesystem for metrics master
      filesystem:
        fstype: "{{ tsuru_fstype }}"
        dev: "/dev/{{ tsuruController_nameVG }}/metrics"
        resizefs: false

    - name: mount prometheus filesystem for metrics master
      mount:
        name: "/var/lib/prometheus"
        src: "/dev/{{ tsuruController_nameVG }}/metrics"
        fstype: "{{ tsuru_fstype }}"
        state: present
  when: isMaster
