---
- name: "ensure Ansible version that is not hit by bug #24430"
  assert:
    that: "ansible_version.full | version_compare('2.4', '>=')"
    msg: "You must update Ansible to at least the version 2.4 to use this role."
  tags: always

- name: setup disk
  tags:
    - tsuru_disk
    - tsuru_worker
  include: disk.yml

- name: setup container service
  tags:
    - tsuru_container
    - tsuru_worker
  include: container.yml
