---
- name: setup disk
  tags:
    - tsuru_disk
    - tsuru_worker
  include: disk.yml

- name: setup container service
  tags:
    - tsuru_container
    - tsuru_worker
  include: container.yml

- name: setup monitoring
  tags:
    - tsuru_monit
    - tsuru_worker
  include: monit.yml
  when: tsuru_monit
