---
- name: "ensure Ansible version that is not hit by bug #24430"
  assert:
    that: "ansible_version.full | version_compare('2.4', '>=')"
    msg: "You must update Ansible to at least the version 2.4 to use this role."
  tags: always

- name: setup disk storage
  tags:
    - tsuru_disk
    - tsuru_router
  include: disk.yml

- name: setup container service
  tags:
    - tsuru_container
    - tsuru_router
  include: container.yml

- name: setup databases
  tags:
    - tsuru_db
    - tsuru_router
  include: db.yml

- name: setup node metrics collection
  tags:
    - tsuru_metrics
    - tsuru_prometheus
  include_role:
    name: stone-payments.prometheus
  vars:
    prometheus_db: false
  when: tsuru_metrics

- name: setup planb router
  tags:
    - tsuru_planb
    - tsuru_router
  include_role:
    name: stone-payments.planb
  vars:
    planb_container_image: "{{ tsuru_routerImage }}"
    planb_container_cmd: "--listen {{ tsuru_addrRouter }}:{{ tsuru_portRouter }}
      --tls-listen {{ tsuru_addrRouter }}:{{ tsuru_portRouterTLS }}
      --read-redis-host 127.0.0.1
      --read-redis-port {{ tsuru_portInMem }}
      --read-redis-password {{ tsuru_passAdmin }}
      --read-redis-db {{ tsuru_redisDB }}
      --dial-timeout {{ tsuru_dialTimeoutRouter }}
      --request-timeout {{ tsuru_requestTimeoutRouter }}
      --write-redis-sentinel-name {{ tsuru_nameMaster }}
      --write-redis-password {{ tsuru_passAdmin }}
      --write-redis-db {{ tsuru_redisDB }}
      --write-redis-sentinel-addrs \"{% for addr in tsuru_addrControllers %}{{ addr }}:{{ tsuru_portSentinel }}{% if not loop.last %},{% endif %}{% endfor %}\""
